spring:
  datasource:
    url: jdbc:postgresql://db:5432/authdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: LmR9+u7JzN2k3Vj1XbZkYWQ3v3XyYJPe+F4gU/GJuS4=
  expiration-ms: 3600000    # 1
  refresh-expiration-ms: 86400000  # 24

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
